data:
  raw_data_path: "data/raw/dataset.csv"
  processed_data_path: "data/processed/processed_data.csv"

model:
  type: "LinearRegression"
  parameters:
    fit_intercept: true
    normalize: false

training:
  test_size: 0.2
  random_state: 42
